### ISSUE TITLE
test failure when builing Dotwebstack Frontend - Openapi

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [dotwebstack/dotwebstack-framework#209]
I cloned the stack to windows and did a  mvn clean install.  
Building went ok until the openapi part.  Soms kind of test failure:

[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ dotwebstack-frontend-openapi ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.dotwebstack.framework.frontend.openapi.mappers.RequestMapperTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.581 s - in org.dotwebstack.framework.frontend.openapi.mappers.RequestMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.testutils.OpenApiConvertersTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.dotwebstack.framework.frontend.openapi.testutils.OpenApiConvertersTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.BaseUriFactoryTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.391 s - in org.dotwebstack.framework.frontend.openapi.BaseUriFactoryTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.cors.CorsResponseFilterTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.202 s - in org.dotwebstack.framework.frontend.openapi.cors.CorsResponseFilterTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.backend.Rdf4jRepositoryBackendTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.236 s - in org.dotwebstack.framework.frontend.openapi.entity.backend.Rdf4jRepositoryBackendTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.backend.Rdf4jValueBackendTest
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.backend.Rdf4jValueBackendTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.EntityWriterInterceptorTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.278 s - in org.dotwebstack.framework.frontend.openapi.entity.EntityWriterInterceptorTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.GraphEntityMapperTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in org.dotwebstack.framework.frontend.openapi.entity.GraphEntityMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.GraphEntityTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.151 s - in org.dotwebstack.framework.frontend.openapi.entity.GraphEntityTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.LdPathExecutorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.122 s - in org.dotwebstack.framework.frontend.openapi.entity.LdPathExecutorTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.AbstractLinkSchemaMapperTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.AbstractLinkSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.AbstractSchemaMapperTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.09 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.AbstractSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.AbstractSubjectSchemaMapperTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.AbstractSubjectSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.ArraySchemaMapperTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.ArraySchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.BooleanSchemaMapperConstantValueTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.BooleanSchemaMapperConstantValueTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.BooleanSchemaMapperLdPathTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.BooleanSchemaMapperLdPathTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.BooleanSchemaMapperTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.BooleanSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.DateSchemaMapperConstantValueTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.DateSchemaMapperConstantValueTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.DateSchemaMapperLdPathTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.DateSchemaMapperLdPathTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.DateSchemaMapperTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.DateSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.DateTimeSchemaMapperConstantValueTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.DateTimeSchemaMapperConstantValueTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.DateTimeSchemaMapperLdPathTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.DateTimeSchemaMapperLdPathTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.DateTimeSchemaMapperTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.DateTimeSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.DoubleSchemaMapperTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.DoubleSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.FloatSchemaMapperTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.FloatSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.IntegerSchemaMapperTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.IntegerSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.LongSchemaMapperTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.LongSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.NextLinkSchemaMapperTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.NextLinkSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.ObjectSchemaMapperTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.ObjectSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.PrevLinkSchemaMapperTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.PrevLinkSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.SchemaMapperAdapterTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.SchemaMapperAdapterTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.SchemaMapperUtilsTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.SchemaMapperUtilsTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.SelfLinkSchemaMapperTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.SelfLinkSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.StringSchemaMapperContextLinksTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.StringSchemaMapperContextLinksTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.StringSchemaMapperRelativeLinkTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.StringSchemaMapperRelativeLinkTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.schema.StringSchemaMapperTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.schema.StringSchemaMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.entity.TupleEntityMapperTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.dotwebstack.framework.frontend.openapi.entity.TupleEntityMapperTest
[INFO] Running org.dotwebstack.framework.frontend.openapi.handlers.ApiRequestValidatorTest
[ERROR] Tests run: 5, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 0.241 s <<< FAILURE! - in org.dotwebstack.framework.frontend.openapi.handlers.ApiRequestValidatorTest
[ERROR] validate_DoesNotFail_ForValidGetRequest  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NullPointerException: openApi
        at org.dotwebstack.framework.frontend.openapi.handlers.ApiRequestValidatorTest.validate_DoesNotFail_ForValidGetRequest(ApiRequestValidatorTest.java:109)

[ERROR] validate_Fails_WhenRequiredHeaderIsNotSupplied  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError:

Expected: an instance of javax.ws.rs.WebApplicationException
     but: <java.lang.NullPointerException: openApi> is a java.lang.NullPointerException
Stacktrace was: java.lang.NullPointerException: openApi
        at org.dotwebstack.framework.frontend.openapi.OpenApiSpecUtils.extractApiOperations(OpenApiSpecUtils.java:47)
        at org.dotwebstack.framework.frontend.openapi.handlers.ApiRequestValidatorTest.validate_Fails_WhenRequiredHeaderIsNotSupplied(ApiRequestValidatorTest.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
        at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
        at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
        at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)
        at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by joostfarla** [comment]
Which JDK version are you using?

**Comment by GeraldGrootRoessink** [comment]
8.0.1020.14

**Comment by GeraldGrootRoessink** [comment]
updated to 8.0.2120.10. Problem stays the same.

**Comment by GeraldGrootRoessink** [comment]
It's a nullpointer exception  
[ERROR]   ApiRequestValidatorTest.validate_DoesNotFail_ForValidGetRequest:109 » NullPointer
[ERROR]   ApiRequestValidatorTest.validate_Fails_WhenRequiredHeaderIsNotSupplied:132 » NullPointer
[ERROR]   ApiRequestValidatorTest.validate_ThrowsException_WhenRequestContainsInvalidParams:169 » NullPointer

**Comment by GeraldGrootRoessink** [comment]
Can get past this error by adding with the assertion:
    exception.expect(NullPointerException.class);
Not sure what this functionaly means.

**Comment by joostfarla** [comment]
This issue should already be resolved in v0.2.
